GATEWAY = "gateway"
DEVICE = "device"
ACTUATOR = "actuator"

MANUFACTURER_SHELLY = "Shelly"
MANUFACTURER_ESPHOME = "ESPHome"

DEVICE_BLU_HT = "BLU_HT"
DEVICE_BLU_MOTION = "BLU_MOTION"
DEVICE_BLU_DOOR = "BLU_DOOR"
